@startuml
'https://plantuml.com/class-diagram

class ListController{
    main()
    start()
}

class FXController{
    +selectListButton()
    +selectItemButton()
    +displayIncompleteListButton()
    +displayCompleteItemsButton()
    +markListCompleteButton()
    +DisplayListItemsButton()
    +removeListButton()
    +exportListButton()
    +removeItemButton()
    +addListButton()
    +editListNameButton()
    +importSpecifiedListsButton()
    +addItemButton()
    +editItemNameButton()
    +editItemDateButton()
    +exportAllListsButton()
}

class ListAggregate{
    +addList()
    +removeList()
    +getLists()
    +getListItems()
    +getCompleteItems()
    +exportList()
    +exportAllLists()
    +loadList()
    +loadAllLists()
}

class TodoList{
    +editListName()
    +addItemToList()
    +removeItemFromList()
}

class Item{
    -String description
    //Use a list to store the year, month, and day separately.
    -ArrayList<String> Date

    +editItemName()
    +editItemDate()
    +markItemComplete()
}




javafx.Application <|-- ListController
ListController o-- ListAggregate
ListController o- FXController
TodoList *-- Item
ListAggregate o- TodoList
@enduml