@startuml
'https://plantuml.com/class-diagram

class ListController{
    main()
    start()
}

class FXController{
    +selectListButton()
    +selectItemButton()
    +displayIncompleteListButton()
    +displayCompleteItemsButton()
    +markListCompleteButton()
    +DisplayListItemsButton()
    +removeListButton()
    +exportListButton()
    +removeItemButton()
    +addListButton()
    +editListNameButton()
    +importSpecifiedListsButton()
    +addItemButton()
    +editItemNameButton()
    +editItemDateButton()
    +exportAllListsButton()
}

class ListAggregate{
    -ArrayList<TodoList> allLists

    +addList()
    +removeList()
    +getLists()
    +getListItems()
    +getCompleteItems()
    +exportList()
    +exportAllLists()
    +loadList()
    +loadAllLists()
}

class TodoList{
    -String name
    -ArrayList<TodoItem> allItems

    +setName()
    +addItem()
    +removeItem()
    +listAsString()
    +completeItemsAsString()
}

class Item{
    -String name
    -Boolean isComplete

    +setName()
    +setDate()
    +setCompleteFlag()
    +get()
    +getIfComplete()
}




javafx.Application <|-- ListController
ListController o-- ListAggregate
ListController o- FXController
TodoList *-- Item
ListAggregate o- TodoList
@enduml